runtime: go115

service: gopypi
main: ./cmd/registry/main.go

env_variables:
  API_KEY: # Put you API key here
  STORAGE_BACKEND: "GCS"

service_account: gopypi-sa@madproject-271618.iam.gserviceaccount.com
